apiVersion: v1
kind: Pod
metadata:
  name: sim-carla
spec:

  - name: carla-server
    image: docker.io/carlasim/carla:0.9.5
    command: ["/bin/bash", "-c"]
    #args: ["./CarlaUE4.sh", "Town04", "-benchmark", "-carla-server", "-fps=20", "-world-port=2000", "-windowed", "-ResX=1024", "-ResY=1024", "-carla-no-hud"]
    args:
      - ./CarlaUE4.sh /Game/Carla/Maps/Town04 -benchmark -carla-server -fps=20 -world-port=2000 -windowed -ResX=1024 -ResY=1024 -carla-no-hud;
    resources:
      limits:
        memory: 6Gi
        nvidia.com/gpu: 1
        cpu: 1

  

